backend:
  name: github
  repo: ajarindsite/web
  branch: main

site:
  title: Adjarindo Creative Aksara
  base_url: https://website-aaf.pages.dev

collections:
  - name: settings
    label: Pengaturan Website
    files:
      - name: general
        label: Umum
        file: index.html
        fields:
          - name: hero_title
            label: Judul Hero
            type: string
          - name: hero_subtitle
            label: Subtitle Hero
            type: text
          - name: contact_address
            label: Alamat
            type: string
          - name: contact_phone
            label: No WA
            type: string
          - name: contact_email
            label: Email
            type: string
